<?php

namespace Database\Seeders;

use App\Models\TeacherDetail;
use App\Models\User;
use Illuminate\Database\Seeder;

class TeacherSeeder extends Seeder
{
    public function run(): void
    {
        $teachers = [
            [
                'name' => 'Dr. Maria Santos',
                'email' => 'maria@example.com',
                'phone' => '+1 (555) 501-0001',
                'avatar' => '',
                'detail' => [
                    'specialization' => ['Special Education', 'Dyslexia', 'Reading Intervention'],
                    'experience' => 12,
                    'rating' => 4.9,
                    'total_students' => 85,
                    'total_sessions' => 1200,
                    'hourly_rate' => 55,
                    'bio' => 'Dedicated special education specialist with over a decade of experience helping children with dyslexia and reading difficulties. Certified Orton-Gillingham practitioner.',
                    'subjects' => ['English', 'Reading', 'Writing', 'Phonics'],
                    'education' => 'Ed.D. in Special Education, Columbia University',
                    'languages' => ['English', 'Spanish'],
                    'location' => 'New York, NY',
                    'availability' => [
                        ['day' => 'Monday', 'slots' => ['09:00', '10:00', '11:00', '14:00', '15:00']],
                        ['day' => 'Wednesday', 'slots' => ['09:00', '10:00', '11:00', '14:00', '15:00']],
                        ['day' => 'Friday', 'slots' => ['09:00', '10:00', '11:00']],
                        ['day' => 'Saturday', 'slots' => ['10:00', '11:00', '14:00']],
                    ],
                    'certificates' => ['Orton-Gillingham Certified', 'Wilson Reading System', 'Special Education License K-12'],
                    'learning_concerns' => ['Dyslexia', 'Slow Processing', 'Memory Retention'],
                    'strengths_support' => ['Reading', 'Writing', 'Creative Thinking'],
                ],
            ],
            [
                'name' => 'David Chen',
                'email' => 'david@example.com',
                'phone' => '+1 (555) 501-0002',
                'avatar' => '',
                'detail' => [
                    'specialization' => ['ADHD', 'Focus Issues', 'Executive Function Coaching'],
                    'experience' => 9,
                    'rating' => 4.7,
                    'total_students' => 62,
                    'total_sessions' => 950,
                    'hourly_rate' => 50,
                    'bio' => 'ADHD and executive function coach who helps students develop focus strategies, organization skills, and confidence. Uses evidence-based techniques tailored to each child.',
                    'subjects' => ['Mathematics', 'Science', 'Study Skills', 'Executive Function'],
                    'education' => 'M.Ed. in Educational Psychology, UCLA',
                    'languages' => ['English', 'Mandarin'],
                    'location' => 'San Francisco, CA',
                    'availability' => [
                        ['day' => 'Monday', 'slots' => ['15:00', '16:00', '17:00']],
                        ['day' => 'Tuesday', 'slots' => ['15:00', '16:00', '17:00']],
                        ['day' => 'Thursday', 'slots' => ['15:00', '16:00', '17:00']],
                        ['day' => 'Saturday', 'slots' => ['09:00', '10:00', '11:00']],
                    ],
                    'certificates' => ['ADHD Coaching Certification', 'Executive Function Coach', 'Teaching Credential K-8'],
                    'learning_concerns' => ['ADHD', 'Focus Issues'],
                    'strengths_support' => ['Problem Solving', 'Organization', 'Memory'],
                ],
            ],
            [
                'name' => 'Aisha Patel',
                'email' => 'aisha@example.com',
                'phone' => '+1 (555) 501-0003',
                'avatar' => '',
                'detail' => [
                    'specialization' => ['Autism Spectrum', 'Social Skills', 'Sensory Integration'],
                    'experience' => 10,
                    'rating' => 4.8,
                    'total_students' => 45,
                    'total_sessions' => 800,
                    'hourly_rate' => 60,
                    'bio' => 'Autism specialist dedicated to creating a safe, structured learning environment for children on the spectrum. Expert in sensory-friendly teaching methods and social skills development.',
                    'subjects' => ['Social Skills', 'Communication', 'Mathematics', 'Science', 'Art'],
                    'education' => 'M.S. in Applied Behavior Analysis, USC',
                    'languages' => ['English', 'Hindi', 'Gujarati'],
                    'location' => 'Chicago, IL',
                    'availability' => [
                        ['day' => 'Tuesday', 'slots' => ['10:00', '11:00', '14:00', '15:00']],
                        ['day' => 'Wednesday', 'slots' => ['10:00', '11:00', '14:00', '15:00']],
                        ['day' => 'Thursday', 'slots' => ['10:00', '11:00']],
                        ['day' => 'Sunday', 'slots' => ['10:00', '11:00', '14:00']],
                    ],
                    'certificates' => ['BCBA', 'RBT Supervisor', 'Autism Specialist Certification', 'TEACCH Certified'],
                    'learning_concerns' => ['Autism Spectrum', 'Anxiety'],
                    'strengths_support' => ['Communication', 'Creative Thinking', 'Art'],
                ],
            ],
            [
                'name' => 'Rachel Thompson',
                'email' => 'rachel@example.com',
                'phone' => '+1 (555) 501-0004',
                'avatar' => '',
                'detail' => [
                    'specialization' => ['Dyscalculia', 'Math Intervention', 'Slow Processing'],
                    'experience' => 7,
                    'rating' => 4.6,
                    'total_students' => 38,
                    'total_sessions' => 600,
                    'hourly_rate' => 48,
                    'bio' => 'Math intervention specialist who makes numbers accessible for every learner. Specializes in dyscalculia and slow processing speed using multi-sensory math techniques.',
                    'subjects' => ['Mathematics', 'Physics', 'Computer Science'],
                    'education' => 'B.Ed. in Mathematics Education, University of Texas',
                    'languages' => ['English'],
                    'location' => 'Austin, TX',
                    'availability' => [
                        ['day' => 'Monday', 'slots' => ['16:00', '17:00', '18:00']],
                        ['day' => 'Wednesday', 'slots' => ['16:00', '17:00', '18:00']],
                        ['day' => 'Friday', 'slots' => ['14:00', '15:00', '16:00']],
                        ['day' => 'Saturday', 'slots' => ['09:00', '10:00', '11:00']],
                    ],
                    'certificates' => ['Math Intervention Specialist', 'Dyscalculia Tutor Training', 'Multi-sensory Math Instruction'],
                    'learning_concerns' => ['Dyscalculia', 'Slow Processing'],
                    'strengths_support' => ['Problem Solving', 'Math Skills'],
                ],
            ],
            [
                'name' => 'Michael Okonkwo',
                'email' => 'michael@example.com',
                'phone' => '+1 (555) 501-0005',
                'avatar' => '',
                'detail' => [
                    'specialization' => ['Anxiety', 'Memory Retention', 'Study Skills'],
                    'experience' => 6,
                    'rating' => 4.5,
                    'total_students' => 50,
                    'total_sessions' => 700,
                    'hourly_rate' => 45,
                    'bio' => 'Patient and encouraging tutor who helps students overcome learning anxiety and build memory retention strategies. Creates a calm, pressure-free learning atmosphere.',
                    'subjects' => ['English', 'History', 'Geography', 'Biology'],
                    'education' => 'M.A. in Clinical Psychology, NYU',
                    'languages' => ['English', 'French'],
                    'location' => 'Boston, MA',
                    'availability' => [
                        ['day' => 'Tuesday', 'slots' => ['14:00', '15:00', '16:00', '17:00']],
                        ['day' => 'Thursday', 'slots' => ['14:00', '15:00', '16:00', '17:00']],
                        ['day' => 'Saturday', 'slots' => ['11:00', '14:00', '15:00']],
                        ['day' => 'Sunday', 'slots' => ['11:00', '14:00', '15:00']],
                    ],
                    'certificates' => ['Cognitive Behavioral Therapy Basics', 'Memory Techniques Certification', 'Teaching License'],
                    'learning_concerns' => ['Anxiety', 'Memory Retention'],
                    'strengths_support' => ['Writing', 'Communication', 'Memory'],
                ],
            ],
            [
                'name' => 'Dr. Sarah Mitchell',
                'email' => 'sarahm@example.com',
                'phone' => '+1 (555) 501-0006',
                'avatar' => '',
                'detail' => [
                    'specialization' => ['Speech & Language', 'Reading Comprehension', 'Phonics'],
                    'experience' => 14,
                    'rating' => 4.9,
                    'total_students' => 120,
                    'total_sessions' => 1800,
                    'hourly_rate' => 65,
                    'bio' => 'Speech-language pathologist and reading specialist. Helps children with language-based learning differences build strong reading comprehension and communication skills.',
                    'subjects' => ['English', 'Reading', 'Writing', 'Speech', 'Phonics'],
                    'education' => 'Ph.D. in Speech-Language Pathology, Northwestern University',
                    'languages' => ['English'],
                    'location' => 'Seattle, WA',
                    'availability' => [
                        ['day' => 'Monday', 'slots' => ['08:00', '09:00', '10:00', '11:00']],
                        ['day' => 'Tuesday', 'slots' => ['08:00', '09:00', '10:00', '11:00']],
                        ['day' => 'Wednesday', 'slots' => ['08:00', '09:00', '10:00', '11:00']],
                        ['day' => 'Thursday', 'slots' => ['14:00', '15:00', '16:00']],
                    ],
                    'certificates' => ['CCC-SLP', 'Reading Specialist License', 'Wilson Reading System Level II'],
                    'learning_concerns' => ['Dyslexia', 'Slow Processing'],
                    'strengths_support' => ['Reading', 'Writing', 'Communication'],
                ],
            ],
            [
                'name' => 'Jordan Lee',
                'email' => 'jordan@example.com',
                'phone' => '+1 (555) 501-0007',
                'avatar' => '',
                'detail' => [
                    'specialization' => ['STEM', 'Computer Science', 'Hands-on Learning'],
                    'experience' => 5,
                    'rating' => 4.7,
                    'total_students' => 30,
                    'total_sessions' => 400,
                    'hourly_rate' => 42,
                    'bio' => 'STEM educator who makes science and technology accessible through hands-on projects and experiments. Great for kinesthetic learners who need to build and do.',
                    'subjects' => ['Computer Science', 'Physics', 'Chemistry', 'Mathematics', 'Robotics'],
                    'education' => 'B.S. in Computer Engineering, MIT',
                    'languages' => ['English', 'Korean'],
                    'location' => 'Portland, OR',
                    'availability' => [
                        ['day' => 'Monday', 'slots' => ['14:00', '15:00', '16:00', '17:00']],
                        ['day' => 'Wednesday', 'slots' => ['14:00', '15:00', '16:00', '17:00']],
                        ['day' => 'Friday', 'slots' => ['14:00', '15:00', '16:00']],
                        ['day' => 'Saturday', 'slots' => ['10:00', '11:00', '14:00']],
                    ],
                    'certificates' => ['STEM Education Certificate', 'Robotics Coach', 'Google Certified Educator'],
                    'learning_concerns' => ['Focus Issues'],
                    'strengths_support' => ['Curiosity', 'Creative Thinking', 'Problem Solving'],
                ],
            ],
            [
                'name' => 'Dr. Emily Foster',
                'email' => 'emilyf@example.com',
                'phone' => '+1 (555) 501-0008',
                'avatar' => '',
                'detail' => [
                    'specialization' => ['Gifted Education', 'Twice-Exceptional (2e)', 'Enrichment'],
                    'experience' => 11,
                    'rating' => 4.8,
                    'total_students' => 55,
                    'total_sessions' => 900,
                    'hourly_rate' => 58,
                    'bio' => 'Specialist in twice-exceptional (2e) learners — gifted students with learning differences. Provides enrichment while supporting areas of need with patience and creativity.',
                    'subjects' => ['Mathematics', 'Science', 'Art', 'Music', 'Creative Writing'],
                    'education' => 'Ph.D. in Gifted Education, Vanderbilt University',
                    'languages' => ['English', 'German'],
                    'location' => 'Denver, CO',
                    'availability' => [
                        ['day' => 'Monday', 'slots' => ['15:00', '16:00', '17:00']],
                        ['day' => 'Tuesday', 'slots' => ['15:00', '16:00', '17:00']],
                        ['day' => 'Wednesday', 'slots' => ['09:00']],
                        ['day' => 'Thursday', 'slots' => ['15:00', '16:00', '17:00']],
                        ['day' => 'Sunday', 'slots' => ['09:00', '10:00', '11:00']],
                    ],
                    'certificates' => ['Gifted Education Specialist', '2e Teaching Certification', 'National Board Certified Teacher'],
                    'learning_concerns' => ['Anxiety', 'Focus Issues', 'Autism Spectrum'],
                    'strengths_support' => ['Creative Thinking', 'Curiosity', 'Problem Solving', 'Leadership'],
                ],
            ],
        ];

        foreach ($teachers as $data) {
            $detail = $data['detail'];
            unset($data['detail']);

            $user = User::create($data + ['role' => 'teacher', 'password' => bcrypt('password')]);

            TeacherDetail::create([
                'user_id' => $user->id,
                'specialization' => $detail['specialization'],
                'experience' => $detail['experience'],
                'rating' => $detail['rating'],
                'total_students' => $detail['total_students'],
                'total_sessions' => $detail['total_sessions'],
                'hourly_rate' => $detail['hourly_rate'],
                'bio' => $detail['bio'],
                'subjects' => $detail['subjects'],
                'education' => $detail['education'],
                'languages' => $detail['languages'],
                'location' => $detail['location'],
                'availability' => $detail['availability'],
                'certificates' => $detail['certificates'],
                'learning_concerns' => $detail['learning_concerns'] ?? [],
                'strengths_support' => $detail['strengths_support'] ?? [],
            ]);
        }

        $this->command->info('Created ' . count($teachers) . ' special needs specialist teachers.');
    }
}
